Controllers/OrderController.cs
using CM.Models;
using CM.ViewModel;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CM.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private ApplicationDbContext _context;
        private List<OrderViewModel> _orderViewModelLst;

        public OrderController()
        {
            _context = new ApplicationDbContext();
            _orderViewModelLst = new List<OrderViewModel>();
        }
        public ActionResult PlaceOrder(CheckoutViewModel checkoutViewModel)
        {

            return View();
        }
        public ActionResult Orders()
        {
            string userId = User.Identity.GetUserId();
            IEnumerable<Order> orders = _context.Orders.Where(o => o.ApplicationUser_Id == userId).ToList();
            foreach (var order in orders)
            {
                var product = _context.Products.Single(p => p.ProductId == order.ProductId);
                var address = _context.Addresses.Single(a => a.AddressId == order.ShippingAddressId);
                OrderViewModel orderViewModel = new OrderViewModel()
                {
                    OrderId = order.OrderId,
                    OrderDate = order.OrderDate,
                    ProductId = order.ProductId,
                    GrandTotal = order.GrandTotal,
                    PaymentMethod = order.CardId.ToString(),
                    ProductName = product.Name,
                    ShippingAddress = address,
                    ShipTo = address.FullName,
                    UnitPrice = product.CurrentPrice
                    
                }; 
                _orderViewModelLst.Add(orderViewModel);
            }
            return View(_orderViewModelLst);
        }
        public ActionResult CancelOrder()
        {
            return View();
        }
        public ActionResult CancelItem()
        {
            return View();
        }
        public ActionResult TrackPackage()
        {
            return View();
        }
        public ActionResult ViewEditOrder()
        {
            return View();
        }

        private List<Address> GetAddresses(string userId)
        {
            List<Address> addressList = new List<Address>();
            if (_context.Addresses.Count() != 0)
            {
                addressList = _context.Addresses.ToList();

            }

            return addressList;
        }
        private List<Card> GetCards(string userId)
        {
            List<Card> cards = new List<Card>();
            if (_context.Cards.Count() != 0)
            {
                cards = _context.Cards.ToList();
            }
            return cards;
        }
        private List<DisplaySelectedItem> GetOrderItems(string userId)
        {
            //List<SelectedItem> orderItems = _context.SelectedItems.Where(s => s.Status == SelectedItemStatus.intTheCart && s.UserId == userId).ToList();
            var orderItems = new List<DisplaySelectedItem>();
            var queryItems = from s in _context.SelectedItems
                             join p in _context.Products
                             on s.ProductId equals p.ProductId
                             where s.Status == 0
                             where s.UserId == userId
                             select new
                             {
                                 productName = p.Name,
                                 productDescription = p.ProductDescription,
                                 price = p.CurrentPrice,
                                 tax = p.Tax

                             };
            foreach (var queryItem in queryItems)
            {
                DisplaySelectedItem displaySelectedItem = new DisplaySelectedItem();
                displaySelectedItem.PName = queryItem.productName;
                displaySelectedItem.PDescription = queryItem.productDescription;
                displaySelectedItem.PPrice = queryItem.price;
                displaySelectedItem.Tax = queryItem.tax;
                orderItems.Add(displaySelectedItem);

            }
            return orderItems;
        }
    }
}

Views/Shared/_CartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, innitial-sacle = 1.0" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @*@Styles.Render("~/Content/css")*@
    @*@Styles.Render("~/Content/Journal.css")*@
    @Styles.Render("~/Content/Flatly.css")
    @*@Styles.Render("~/Content/Cerulean.css")*@
    @*@Styles.Render("~/Content/Readable.css")*@
    @*@Styles.Render("~/Content/Sandstone.css")*@
    @*@Styles.Render("~/Content/Simplex.css")*@
    @*@Styles.Render("~/Content/Slet.css")
    @Styles.Render("~/Content/SpaceLab.css")
    @Styles.Render("~/Content/Superhero.css")
    @Styles.Render("~/Content/Yeti.css")*@
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Mike CM System", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-left">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Products", "GetAllProducts", "Product")</li>
                <li>@Html.ActionLink("Add a product", "AddProduct", "Product")</li>
                <li>
                    @Html.ActionLink("Cart", "Cart", "Product")
                </li>
                <li>@Html.ActionLink("Saved for later", "SaveForLater", "Product")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

<div class="container-fluid">
        <div class="row">
            <div class="col col-lg-2"></div>
            <div class="col col-lg-6">
                @RenderBody()
            </div>
            <div class="col col-lg-1"></div>
            <div class="col col-lg-3">
                @RenderSection("rightNavBar", false)
            </div>
        </div>
        <div class="row">
            <div class="col col-lg-12">
            </div>
        </div>


        <div style="position: fixed; bottom: 0; text-align: center">
            <footer>
                <p>&copy; @DateTime.Now.Year - Mike CM System</p>
            </footer>
        </div>


        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @*@RenderSection("scripts", required: false)*@
        @RenderSection("myScript", required: false)
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
@using System.Web.UI.WebControls
@using CM.Controllers
@using CM.Models
@using Microsoft.Ajax.Utilities
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/Journal.css")
    @*@Styles.Render("~/Content/Flatly.css")*@
    @*@Styles.Render("~/Content/Cerulean.css")*@
    @*@Styles.Render("~/Content/Readable.css")*@
    @*@Styles.Render("~/Content/Sandstone.css")*@
    @*@Styles.Render("~/Content/Simplex.css")
    @Styles.Render("~/Content/Slet.css")
    @Styles.Render("~/Content/SpaceLab.css")
    @Styles.Render("~/Content/Superhero.css")
    @Styles.Render("~/Content/Yeti.css")*@
    
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Mike CM System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-left">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
 
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Products", "GetAllProducts", "Product")</li>
                <li>@Html.ActionLink("Add a product", "AddProduct", "Product")</li>
                <li>
                    @Html.ActionLink("Cart", "Cart", "Product")
                </li>
                <li>@Html.ActionLink("Saved for later", "SaveForLater", "Product")</li>
                <li>@Html.ActionLink("Orders", "Orders", "Order")</li>

                <li class="active">
                    <a href="@Url.Action("Cart", "Product")" class="btn btn-clear btn-lg">
                        <span class="glyphicon glyphicon-shopping-cart"></span><b>Cart</b>
                        @if (User.Identity.GetUserId() != null)
                        {
                            <span class="badge">@HomeController.itemCountForUser</span>
                        }
                        else
                        {
                            <span class="badge">@HomeController.itemCountForAnonymous</span>
                        }
                    </a>
                </li>
            </ul>

                @Html.Partial("_LoginPartial")
</div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col col-lg-12"></div>
    </div>
    <div class="row">
        <div class="col col-lg-2">
           
        </div>
        <div class="col col-lg-7">
            @RenderBody()
        </div>
        <div class="col col-lg-3">
            @RenderSection("rightNavBar", false)
        </div>
    </div>
    <div class="row">
        <div class="col col-lg-12">
            <p>&copy; @DateTime.Now.Year - Mike CM System</p>
        </div>
    </div>


    @*<table style="width: 2000px">
        <tr>
        <td>

        <tr>
            <td style="width: 200px"></td>
            <td style="width: 1300px">
                <div class="container body-content">
                    @RenderBody()
                </div>
            </td>
            <td style="width: 500px"></td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                <div class="container body-content">
                    <footer>
                        <p>&copy; @DateTime.Now.Year - Mike CM System</p>
                    </footer>
                </div>
            </td>
        </tr>
    </table>*@
</div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
    @RenderSection("myScript", required: false)




</body>
</html>