Controllers/CardController.cs
using CM.Models;
using System.Web.Mvc;
using CM.ViewModel;
using Microsoft.AspNet.Identity;

namespace CM.Controllers
{
    public class CardController : Controller
    {
        private ApplicationDbContext _context;

        public CardController()
        {
            _context = new ApplicationDbContext();
        }

        [Authorize]
        [HttpGet]
        [ActionName("AddCard")]
        public ActionResult AddCard_Get()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ActionName("AddCard")]
        public ActionResult AddCard_Post(Card cardObj)
        {
            Card card = new Card()
            {
                ApplicationUser_Id = User.Identity.GetUserId(),
                CardNumber = cardObj.CardNumber,
                NameOnCard = cardObj.NameOnCard,
                ExpirationDate = cardObj.ExpirationDate
            };
            if (ModelState.IsValid)
            {
                _context.Cards.Add(card);
                _context.SaveChanges();
                return RedirectToAction("Checkout", "CheckOut");
            }
            return View();
        }
    }
}

Controllers/CheckOutController.cs
using CM.Models;
using CM.ViewModel;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CM.Controllers
{
    public class CheckOutController : Controller
    {
        private ApplicationDbContext _context;


        [HttpGet]
        [ActionName("AddCard")]
        public ActionResult AddCard_Get(string userId)
        {
            return View();
        }

        [HttpPost]
        [ActionName("AddCard")]
        public ActionResult AddCard_Post(Card cardObj)
        {
            if (ModelState.IsValid)
            {
                Card card = new Card()
                {
                    ApplicationUser_Id = cardObj.ApplicationUser_Id,
                    CardNumber = cardObj.CardNumber,
                    NameOnCard = cardObj.NameOnCard,
                    ExpirationDate = cardObj.ExpirationDate
                };
                _context.Cards.Add(card);
            _context.SaveChanges();
            return RedirectToAction("Checkout", "CheckOut");
            }
            return View();

        }
        public CheckOutController()
        {
            _context = new ApplicationDbContext();
        }

        [HttpGet]
        [ActionName("Checkout")]
        public ActionResult Checkout_Get()
        {
            CheckoutViewModel checkoutViewModel = new CheckoutViewModel();
            ActionResult view;
            var userId = User.Identity.GetUserId();
            if (userId != null)
            {
                checkoutViewModel.Addresses = GetAddresses(userId);
                checkoutViewModel.Cards = GetCards(userId);
                checkoutViewModel.OrderItems = GetOrderItems(userId);
                view = View(checkoutViewModel);
            }
            else
            {
                checkoutViewModel.Addresses = GetAddresses("anonymous");
                checkoutViewModel.Cards = GetCards("anonymous");
                checkoutViewModel.OrderItems = GetOrderItems("anonymous");
                view = View(checkoutViewModel);
            }
            return view;
        }

        [HttpPost]
        [ActionName("Checkout")]
        public ActionResult Checkout_Post(int addressId, int cardId, int productId, int? quantity)
        {
            Product product = _context.Products.Single(p => p.ProductId == productId);
            decimal? subtotal = product.CurrentPrice.Value * quantity.Value;
            decimal? tax = subtotal*.1M;
            decimal? grandtotal = subtotal + tax;
            var itemInCart = _context.SelectedItems.Single(s => s.ProductId == productId);
            itemInCart.Status = SelectedItemStatus.deleted;

            Order order = new Order()
            {
                OrderDate = DateTimeOffset.Now,
                ApplicationUser_Id = User.Identity.GetUserId(),
                CardId = cardId,
                GrandTotal = grandtotal,
                Tax = .1M,
                ShippingAddressId = addressId,
                OrderItems = _context.SelectedItems.Where(s => s.Status == SelectedItemStatus.intTheCart).ToList(),
                ProductId = productId
            };
            _context.Orders.Add(order);
            _context.SaveChanges();
            return RedirectToAction("PlaceOrder", "Order");
            
        }

        [HttpGet]
        [ActionName("AddAddress")]
        public ActionResult AddAddress_Get()
        {
            return View();
        }     
        
        [HttpPost]
        [ActionName("AddAddress")]
        public ActionResult AddAddress_Post(Address address, string userId)
        {
            userId = User.Identity.GetUserId();
            Address ad = new Address()
            {
                FullName = address.FullName,
                City = address.City,
                Country = address.Country,
                State = address.State,
                StreetLine1 = address.StreetLine1,
                ZipCode = address.ZipCode
                //ApplicationUser_Id = userId
            };
            if (ModelState.IsValid)
            {
                _context.Addresses.Add(ad);
                _context.SaveChanges();
                return RedirectToAction("Checkout", "CheckOut");
            }
            return View();
        }

        [HttpGet]
        [ActionName("EditAddress")]
        public ActionResult EditAddress_Get(int addressId)
        {
            var address = _context.Addresses.Single(ad => ad.AddressId == addressId);
            return View(address);
        }

        [HttpPost]
        [ActionName("EditAddress")]
        public ActionResult EditAddress_Post(Address addressObj)
        {
           //r address = _context.Addresses.Single(ad => ad.AddressId.ToString() == "1");

            // Query the database for the row to be updated.
            var query =
                from address in _context.Addresses
                where address.AddressId.ToString() == "1"
                select address;

            // Execute the query, and change the column values you want to change.
            foreach (Address ad in query)
            {
                //ad.ApplicationUser_Id = addressObj.ApplicationUser_Id;
                ad.FullName = addressObj.FullName;
                ad.StreetLine1 = addressObj.StreetLine1;
                ad.StreetLine2 = addressObj.StreetLine2;
                ad.City = addressObj.City;
                ad.State = addressObj.State;
                ad.Country = addressObj.Country;
            }

            // Submit the changes to the database.
            try
            {
                _context.SaveChanges();
            }
            catch (Exception e)
            {
                
                // Provide for exceptions.
            }
            return RedirectToAction("Checkout", "CheckOut");
        }

        #region Helper method
        private List<Address> GetAddresses(string userId)
        {
            List<Address> addressList = new List<Address>();
            if (_context.Addresses.Count() != 0)
            {
                addressList = _context.Addresses.ToList();

            }

            return addressList;
        }
        private List<Card> GetCards(string userId)
        {
            List<Card> cards = new List<Card>();
            if (_context.Cards.Count() != 0)
            {
                cards = _context.Cards.Where(c => c.ApplicationUser_Id == userId).ToList();
            }
            return cards;
        }
        private List<DisplaySelectedItem> GetOrderItems(string userId)
        {
           //List<SelectedItem> orderItems = _context.SelectedItems.Where(s => s.Status == SelectedItemStatus.intTheCart && s.UserId == userId).ToList();
            var orderItems = new List<DisplaySelectedItem>();
           var queryItems = from s in _context.SelectedItems
                join p in _context.Products
                on s.ProductId equals p.ProductId
                where s.Status == 0
                where s.UserId == userId
                select new
                {
                    productId = p.ProductId,
                    productName = p.Name,
                    productDescription = p.ProductDescription,
                    price = p.CurrentPrice,
                    tax = p.Tax

                };
            foreach (var queryItem in queryItems)
            {
                DisplaySelectedItem displaySelectedItem = new DisplaySelectedItem();
                displaySelectedItem.ProductId = queryItem.productId;
                displaySelectedItem.PName = queryItem.productName;
                displaySelectedItem.PDescription = queryItem.productDescription;
                displaySelectedItem.PPrice = queryItem.price;
                displaySelectedItem.Tax = queryItem.tax;
                orderItems.Add(displaySelectedItem);

            }
            return orderItems;
        }
	    #endregion    
    }
}

Views/CheckOut/AddAddress.cshtml
@model CM.Models.Address
@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_CartLayout.cshtml";

}

@using (Html.BeginForm("AddAddress", "CheckOut"))
{
    <div style="position: fixed; top: 40px">
        <table class="table">
            <tr>
                <th>
                    <h2>Add your address</h2>
                </th>
            </tr>
            <tr>
                <td width="600px">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(a => a.AddressId)


                    <div class="form-group">
                        @Html.LabelFor(a => a.FullName)
                        @Html.TextBoxFor(a => a.FullName, new { @class = "form-control" })
                        @Html.ValidationMessage("FullName", new { @class = "field-validation-error text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.StreetLine1)
                        @Html.TextBoxFor(a => a.StreetLine1, new { @class = "form-control" })
                        @Html.ValidationMessage("StreetLine1", new { @class = "field-validation-error text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.StreetLine2)
                        @Html.TextBoxFor(a => a.StreetLine2, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.City)
                        @Html.TextBoxFor(a => a.City, new { @class = "form-control" })
                        @Html.ValidationMessage("City", new { @class = "field-validation-error text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.State)
                        @Html.DropDownListFor(a => a.State, new SelectList(new List<string>()
                        {"AK", "AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS",
                            "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
                            "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
                        }), "Select State", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.ZipCode)
                        @Html.TextBoxFor(a => a.ZipCode, new { @class = "form-control" })
                        @Html.ValidationMessage("ZipCode", new { @class = "field-validation-error text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.Country)
                        @Html.DropDownListFor(a => a.Country, new SelectList(new List<string>() { "United States" }), new { @class = "form-control" })
                        @Html.ValidationMessage("Country", new { @class = "field-validation-error text-danger" })
                    </div>
                    <div class="form-group">
                        @Html.CheckBoxFor(a => a.UseThisAddress)
                        @Html.LabelFor(a => a.UseThisAddress)
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save</button> |
                        @Html.ActionLink("Cancel", "CheckOut")
                    </div>
                </td>
                <td></td>
            </tr>
        </table>
    </div>
}

Views/CheckOut/AddCard.cshtml
@model CM.Models.Card

@{
    ViewBag.Title = "AddCard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br/>
<br/>
<br/>
<h2>Add a debit card or credit card</h2>

@using (Html.BeginForm("AddCard", "CheckOut"))
{
    @Html.ValidationSummary(true)
    @Html.HiddenFor(c => c.ApplicationUser_Id)
    <div class="form-group">
        @Html.LabelFor(c => c.NameOnCard)
        @Html.TextBoxFor(c => c.NameOnCard, new{@class="form-control"})
        @Html.ValidationMessage("NameOnCard", new {@class = "field-validation-error text-danger"})
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.CardNumber)
        @Html.TextBoxFor(c => c.CardNumber, new{@class="form-control"})
        @Html.ValidationMessage("CardNumber", new {@class = "field-validation-error text-danger"})
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.ExpirationDate)
        @Html.TextBoxFor(c => c.ExpirationDate, new{@class="form-control"})
        @Html.ValidationMessage("NameOnCard", new {@class = "field-validation-error text-danger"})
    </div>
        <button class="btn alert-info" type="submit">Save</button>
}

Views/CheckOut/Checkout.cshtml
@model CM.ViewModel.CheckoutViewModel
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_CartLayout.cshtml";
    int sum = 0;
}
<br/>
<br/>
<br/>
<h1>Check out</h1>
<form action="/Checkout/Checkout" method="post">
    @*<button class="btn btn-success btn-lg" data-toggle="collapse" data-target="#addressInfo">Address information</button>*@
    <div class="btn btn-sm" data-toggle="collapse" data-target="#addressInfo">
        <h3 style="color: darkorange">1. Choose shipping address</h3>
    </div>
    <div id="addressInfo" class="panel panel-default">
        <table id="address" class="table">
            <tr>
                <td><b>Shipping address: </b></td>

                <td>
                    @foreach (var ad in Model.Addresses)
                {
                        <h4><input type="radio" name="addressId" value="@ad.AddressId" /> @ad.FullName</h4>
                        @ad.StreetLine1<br />
                        @ad.City
                        @ad.State<br />
                        @ad.ZipCode<br />
                        @ad.Country
                        <br />
                        @Html.ActionLink("Edit", "EditAddress", "CheckOut", new {addressId = ad.AddressId}, null)
                }
                </td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <a href='@Url.Action("AddAddress", "CheckOut")'>Add new address</a>
                </td>
            </tr>
        </table>

    </div>

    @*<button class="btn btn-success btn-lg" data-toggle="collapse" data-target="#paymentInfo">Payment information</button>*@
    <div class="btn" data-toggle="collapse" data-target="#paymentInfo">
        <h3 style="color: darkorange">2. Choose a payment method</h3>
    </div>
    <div id="paymentInfo" class="panel panel-default">
        <table id="paymentMethod" class="table">
            <tr>
                <td><b>card ending in:</b></td>
                <td><b>Name on card:</b></td>
                <td><b>Expires on:</b></td>
            </tr>
            @foreach (var card in Model.Cards)
        {
                <tr>
                    <td><input type="radio" name="cardId" value="@card.CardId" />@card.CardNumber</td>
                    <td>@card.NameOnCard</td>
                    <td>@card.ExpirationDate.ToShortDateString()</td>
                </tr>
        }
            <tr>
                <td>
                    <a href='@Url.Action("AddCard", "Card")'>Add a card</a>
                </td>
            </tr>
        </table>
    </div>

    @*<button class="btn btn-success btn-lg" data-toggle="collapse" data-target="#orderSummaryInfo">Order summary</button>*@
    <div class="btn" data-toggle="collapse" data-target="#orderSummaryInfo">
        <h3 style="color: darkorange">3. Review your order</h3>
    </div>
    <div id="orderSummaryInfo" class="panel panel-default">
        <table id="orderSummary" class="table">
            @foreach (var item in Model.OrderItems)
            {
                <tr class="panel panel-default">
                    <td>
                        <img src="~/Images/s8.jpg" alt="Product image" />
                    </td>
                    <td>
                        <div class="row">
                            <div class="col-lg-7">
                                <input id="ProductId" name="ProductId" type="hidden" value="@item.ProductId" />
                                <a href="#"><h4>@item.PName</h4></a>
                                @item.PDescription<br />
                                <h4 class="price" style="color: darkred">@item.PPrice</h4>
                                Qty:<select class="quantity" name="quantity">
                                    <option>0</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>
                                <hr />
                            </div>

                        </div>
                    </td>
                    <td></td>
                </tr>
            }
            <tr>
                <td>
                    <h2 style="color: darkred">Order total before tax:</h2>
                    <h2 style="color: darkred" id="subTotal"></h2>
                </td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td>
                    <button type="submit" class="btn btn-warning">Place your order</button>
                </td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>

    <div style="position: fixed; top: 100px; right: 0;" class="well">
        <div class="row">
            <div class="col col-lg-3"></div>
            <div class="col col-lg-8">
                <button type="submit" class="btn btn-warning">Place your order</button>
            </div>
            <div class="col col-lg-1"></div>
        </div>
        <div class="row">
            <div class="col col-lg-3"></div>
            <div class="col col-lg-8">
                <p>
                    By placing your order, you agree to Mike CM System's privacy notice and conditions of use.
                </p>
            </div>
            <div class="col col-lg-1"></div>
        </div>
        <div class="row">
            <div class="col col-lg-3"></div>
            <div class="col col-lg-8">
                <h2>
                    Order summary
                </h2>
            </div>
            <div class="col col-lg-1"></div>
        </div>
        @foreach (var item in Model.OrderItems)
        {
            <div class="row">
                <div class="col col-lg-3"></div>
                <div class="col col-lg-5">
                    <h4>Total before tax:</h4>
                </div>
                <div class="col col-lg-3">
                    <h4><b id="totalBeforeTax"></b></h4>
                </div>
                <div class="col col-lg-1"></div>
            </div>
            <div class="row">
                <div class="col col-lg-3"></div>
                <div class="col col-lg-5">
                    <h4>Tax(10%):</h4>
                </div>
                <div class="col col-lg-3">
                    <h4><b id="tax"></b></h4>
                </div>
                <div class="col col-lg-1"></div>
            </div>
            <div class="row">
                <div class="col col-lg-3"></div>
                <div class="col col-lg-5">
                    <h2 style="font-weight: bolder; color: darkred">Order total:</h2>
                </div>
                <div class="col col-lg-3">
                    <h2 style="color: darkred" id="total"></h2>
                </div>
                <div class="col col-lg-1"></div>
            </div>
        }
    </div>
</form>
@section myScript
{
    <script src="~/Scripts/myJavaScript.js"></script>

}

Views/CheckOut/EditAddress.cshtml
@model CM.Models.Address
@{
    ViewBag.Title = "ChangeAddress";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Change Address</h2>
@using (Html.BeginForm("EditAddress", "CheckOut"))
{
    <div style="position: fixed; top: 40px">
        <table class="table">
            <tr>
                <th>
                    <h2>Add your address</h2>
                </th>
            </tr>
            <tr>
                <td width="600px">
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(a => a.ApplicationUser_Id)
                    <div class="form-group">
                        @Html.LabelFor(a => a.FullName)
                        @Html.TextBoxFor(a => a.FullName, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.StreetLine1)
                        @Html.TextBoxFor(a => a.StreetLine1, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.StreetLine2)
                        @Html.TextBoxFor(a => a.StreetLine2, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.City)
                        @Html.TextBoxFor(a => a.City, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.State)
                        @Html.DropDownListFor(a => a.State, new SelectList(new List<string>()
                        {"AK", "AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS",
                            "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY",
                            "NC", "ND", "OH", "OK", "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"
                        }), "Select State", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.ZipCode)
                        @Html.TextBoxFor(a => a.ZipCode, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(a => a.Country)
                        @Html.DropDownListFor(a => a.Country, new SelectList(new List<string>() { "United States" }), new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.CheckBoxFor(a => a.UseThisAddress)
                        @Html.LabelFor(a => a.UseThisAddress)
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save</button> |
                        @Html.ActionLink("Cancel", "CheckOut")
                    </div>
                </td>
                <td></td>
            </tr>
        </table>
    </div>
}